package xiaozhi.common.utils;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

public class AESUtilsTest {

    @Test
    public void testEncryptAndDecrypt() {
        String key = "xiaozhi1234567890";
        String plainText = "Hello, xiaozhi!";

        System.out.println("Plain text: " + plainText);
        System.out.println("Key: " + key);

        // Encrypt
        String encrypted = AESUtils.encrypt(key, plainText);
        System.out.println("Encrypted: " + encrypted);

        // Decrypt
        String decrypted = AESUtils.decrypt(key, encrypted);
        System.out.println("Decrypted: " + decrypted);

        // Verify
        assertEquals(plainText, decrypted, "Encryption and decryption results should match");
        System.out.println("Round-trip consistency: " + plainText.equals(decrypted));
    }

    @Test
    public void testDifferentKeyLengths() {
        String[] keys = {
                "1234567890123456", // 16 bytes
                "123456789012345678901234", // 24 bytes
                "12345678901234567890123456789012", // 32 bytes
                "short", // short key
                "verylongkeythatwillbetruncatedto32bytes" // long key
        };

        String plainText = "Test text";

        for (String key : keys) {
            String encrypted = AESUtils.encrypt(key, plainText);
            String decrypted = AESUtils.decrypt(key, encrypted);
            assertEquals(plainText, decrypted, "Key length: " + key.length());
        }
    }

    @Test
    public void testSpecialCharacters() {
        String key = "xiaozhi1234567890";
        String[] testTexts = {
                "Hello World",
                "Hello world",
                "Hello, xiaozhi!",
                "Special characters: !@#$%^&*()",
                "Mixed numbers and Chinese 123",
                "Emoji: 😀🎉🚀",
                "Empty string test",
                ""
        };

        for (String text : testTexts) {
            String encrypted = AESUtils.encrypt(key, text);
            String decrypted = AESUtils.decrypt(key, encrypted);
            assertEquals(text, decrypted, "Test text: " + text);
        }
    }

    @Test
    public void testCrossLanguageCompatibility() {
        // These are the encryption results generated by the Python version, used to test cross-language compatibility
        String key = "xiaozhi1234567890";
        String plainText = "Hello, xiaozhi!";

        // Encryption result generated by the Python version (obtained after running the Python test)
        // String pythonEncrypted = "Encryption result obtained from the Python test";
        // String decrypted = AESUtils.decrypt(key, pythonEncrypted);
        // assertEquals(plainText, decrypted, "Java should be able to decrypt the result encrypted by Python");

        // Generate a Java encryption result for the Python test
        String javaEncrypted = AESUtils.encrypt(key, plainText);
        System.out.println("Java encryption result for Python testing: " + javaEncrypted);
    }
}