package xiaozhi.modules.agent.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;

@Data
@Schema(description = "Agent snapshot restore request")
public class AgentSnapshotRestoreDTO {
    @NotBlank
    @Schema(description = "Current configuration state fingerprint generated by the server during preview")
    private String currentStateToken;
}
