import uniHelper from '@uni-helper/eslint-config'

export default uniHelper({
  unocss: true,
  vue: true,
  markdown: false,
  ignores: [
    'src/uni_modules/',
    'dist',
    // Type file generated by unplugin-auto-import; changes on every commit, so ignore it (paired with .gitignore)
    'auto-import.d.ts',
    // Type file generated by vite-plugin-uni-pages; differs across branch switches, so just .gitignore it
    'uni-pages.d.ts',
    // Files generated by plugins
    'src/pages.json',
    'src/manifest.json',
    // Ignore auto-generated files
    'src/service/app/**',
  ],
  rules: {
    'no-console': 'off',
    'no-unused-vars': 'off',
    'vue/no-unused-refs': 'off',
    'unused-imports/no-unused-vars': 'off',
    'eslint-comments/no-unlimited-disable': 'off',
    'jsdoc/check-param-names': 'off',
    'jsdoc/require-returns-description': 'off',
    'ts/no-empty-object-type': 'off',
    'no-extend-native': 'off',
  },
  formatters: {
    /**
     * Format CSS, LESS, SCSS files, also the `<style>` blocks in Vue
     * By default uses Prettier
     */
    css: true,
    /**
     * Format HTML files
     * By default uses Prettier
     */
    html: true,
  },
})
